package dao;

import model.MSInfo;

public interface MSInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_micro_service_info
     *
     * @mbggenerated Tue Mar 12 14:31:18 AEDT 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_micro_service_info
     *
     * @mbggenerated Tue Mar 12 14:31:18 AEDT 2019
     */
    int insert(MSInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_micro_service_info
     *
     * @mbggenerated Tue Mar 12 14:31:18 AEDT 2019
     */
    int insertSelective(MSInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_micro_service_info
     *
     * @mbggenerated Tue Mar 12 14:31:18 AEDT 2019
     */
    MSInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_micro_service_info
     *
     * @mbggenerated Tue Mar 12 14:31:18 AEDT 2019
     */
    int updateByPrimaryKeySelective(MSInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_micro_service_info
     *
     * @mbggenerated Tue Mar 12 14:31:18 AEDT 2019
     */
    int updateByPrimaryKey(MSInfo record);
}