package model;
import java.io.Serializable;

public class MSInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_micro_service_info.id
     *
     * @mbggenerated Tue Mar 12 14:30:11 AEDT 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_micro_service_info.name
     *
     * @mbggenerated Tue Mar 12 14:30:11 AEDT 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_micro_service_info.version
     *
     * @mbggenerated Tue Mar 12 14:30:11 AEDT 2019
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_micro_service_info
     *
     * @mbggenerated Tue Mar 12 14:30:11 AEDT 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_micro_service_info.id
     *
     * @return the value of tbl_micro_service_info.id
     *
     * @mbggenerated Tue Mar 12 14:30:11 AEDT 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_micro_service_info.id
     *
     * @param id the value for tbl_micro_service_info.id
     *
     * @mbggenerated Tue Mar 12 14:30:11 AEDT 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_micro_service_info.name
     *
     * @return the value of tbl_micro_service_info.name
     *
     * @mbggenerated Tue Mar 12 14:30:11 AEDT 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_micro_service_info.name
     *
     * @param name the value for tbl_micro_service_info.name
     *
     * @mbggenerated Tue Mar 12 14:30:11 AEDT 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_micro_service_info.version
     *
     * @return the value of tbl_micro_service_info.version
     *
     * @mbggenerated Tue Mar 12 14:30:11 AEDT 2019
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_micro_service_info.version
     *
     * @param version the value for tbl_micro_service_info.version
     *
     * @mbggenerated Tue Mar 12 14:30:11 AEDT 2019
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_micro_service_info
     *
     * @mbggenerated Tue Mar 12 14:30:11 AEDT 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MSInfo other = (MSInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_micro_service_info
     *
     * @mbggenerated Tue Mar 12 14:30:11 AEDT 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_micro_service_info
     *
     * @mbggenerated Tue Mar 12 14:30:11 AEDT 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", version=").append(version);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}